[tool.poetry]
name = "innohassle-accounts"
version = "0.1.0"
description = ""
authors = ["Ruslan Bel'kov <ruslan.belckov@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
fastapi = "^0.110.0"
authlib = "^1.2.1"
uvicorn = "^0.28.0"
pyyaml = "^6.0.1"
itsdangerous = "^2.1.2"
python-multipart = "^0.0.9"
colorlog = "^6.8.2"
beanie = "^1.25.0"
pydantic = {extras = ["email"], version = "^2.6.3"}
httpx = "^0.27.0"

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
ruff = "^0.3.2"
pre-commit = "^3.6.2"
pydantic = {extras = ["email"], version = "^2.6.3"}

[tool.ruff]
line-length = 120
lint.ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
