[tool.poetry]
name = "innohassle-accounts"
version = "0.1.0"
description = ""
authors = ["Ruslan Bel'kov <ruslan.belckov@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
fastapi = {extras = ["uvicorn"], version = "^0.103.1"}
sqlalchemy = {extras = ["postgresql-asyncpg"], version = "^2.0.20"}
authlib = "^1.2.1"
uvicorn = "^0.23.2"
itsdangerous = "^2.1.2"
httpx = "^0.25.0"
pydantic-settings = "^2.0.3"
jinja2 = "^3.1.2"
python-multipart = "^0.0.6"


[tool.poetry.group.dev.dependencies]
black = "^23.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
