[tool.poetry]
name = "innohassle-accounts"
version = "0.1.0"
description = ""
authors = ["Ruslan Bel'kov <ruslan.belckov@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
fastapi = "^0.109.2"
authlib = "^1.2.1"
uvicorn = "^0.27.1"
httpx = "^0.26.0"
pydantic = {extras = ["email"], version = "^2.6.1"}
ruff = "^0.2.1"
pyyaml = "^6.0.1"
itsdangerous = "^2.1.2"
motor = "^3.3.2"
motor-types = "^1.0.0b4"
python-multipart = "^0.0.9"
colorlog = "^6.8.2"

[tool.ruff]
line-length = 120
lint.ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
